name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed for trusted publishing
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v1
    - name: Set up Python
      run: uv python install
    - name: Build package
      run: uv build
    - name: Publish package to PyPI
      run: uv publish
